### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by jemo07** [XXIIVV/oscean#114]
https://wiki.xxiivv.com/site/uxnemu.html there is nothing there...

**Comment by neauoire** [comment]
How did you end up there from?

**Comment by jemo07** [comment]
https://llllllll.co/t/uxn-virtual-computer/46103 I clicked on emulator... 

" It was designed with an implementation-first mindset with the goal of targeting [salvaged computers 189](https://wiki.xxiivv.com/site/collapse_computing.html). The distribution of Uxn projects is not unlike downloading a [rom 123](https://wiki.xxiivv.com/site/roms.html) for a console, Uxn has its own [emulator 68](https://wiki.xxiivv.com/site/uxnemu.html)."

**Comment by neauoire** [comment]
Oh! thank you. I guess I can't edit this old thread anymore, but the link is now: https://100r.co/site/uxn.html
