### ISSUE TITLE
404 for /media/diary/000.jpg 

### ISSUE THREAD

**Issue by SteGriff** [XXIIVV/oscean#115]
Hi Devine,

The page https://wiki.xxiivv.com/site/nataniev.html includes the image https://wiki.xxiivv.com/media/diary/000.jpg twice, and it's not found.

Thanks!
Ste

**Comment by neauoire** [comment]
Thanks! 

Turns out I could solve this by removing [24 lines](https://github.com/XXIIVV/oscean/commit/f6bfe7f6b6e412490c40c53191a2b71f862df42c#diff-b0a699ba6474b72978e52307b166fb0e565d883e6dc13badf8752e1892a33f55).
