### ISSUE TITLE
Broken link on https://git.sr.ht/~rabbits/uxn readme.

### ISSUE THREAD

**Issue by sam-falvo** [XXIIVV/oscean#117]
There is a link which reads "XXIIVV — uxntal cheatsheet" and points to https://wiki.xxiivv.com/site/uxntal_cheatsheet.html .  However, when I click on it, I get to a page which reads:

> "
> 
> Your destination could not be found, please [report the broken route](https://github.com/XXIIVV/oscean/issues/new), or visit the [index](https://wiki.xxiivv.com/site/index.html).

Is the link broken, or has the cheatsheet simply not yet been completed?

**Comment by sam-falvo** [comment]
On second thought, this ticket is irrelevant; I will open the issue on the referenced repo instead.

**Comment by neauoire** [comment]
hey sam :) Where was this page linked from?
The cheatsheet was merged into the main uxntal page since: http://wiki.xxiivv.com/site/uxntal.html

**Comment by sam-falvo** [comment]
When I visit https://git.sr.ht/~rabbits/uxn on my Firefox browser, under the *Need a hand?* heading.

**Comment by neauoire** [comment]
ah! perfect thanks, removed link
