### ISSUE TITLE
Broken link to uxntal cheatsheet

### ISSUE THREAD

**Issue by andreer** [XXIIVV/oscean#119]
From https://100r.co/site/uxn.html , there is a broken link to "Uxntal cheatsheet(XXIIVV)": https://wiki.xxiivv.com/site/uxntal_cheatsheet.html

Unrelated praise and gossip: Uxn is awesome, you guys make super cool stuff. Hoping to be able to share a new implementation soon!

**Comment by neauoire** [comment]
Thanks! Removed link to old cheatsheet, the cheatsheet has been merged into the [uxntal page](http://wiki.xxiivv.com/site/uxntal.html).
