### ISSUE TITLE
Time undefined on #horaire

### ISSUE THREAD

**Issue by kormyen** [XXIIVV/Oscean#23]
> Uncaught TypeError: Cannot read property 'time' of undefined
> at Status.toString (status.js:9)
> at status (heol.js:191)
> at interpretList (lisp.js:48)
> at interpret (lisp.js:55)
> at interpret (lisp.js:53)
> at Heol.Lisp.toString (lisp.js:103)
> at Object.heol [as fn] (runic.js:73)
> at stash.a.reduce (runic.js:38)
> at Array.reduce (<anonymous>)
> at _html (runic.js:36)

on

https://wiki.xxiivv.com/#horaire

Chrome 71, macOS 10.14.2

![image](https://user-images.githubusercontent.com/836507/52540252-89dcee00-2dec-11e9-97b7-ab713dee1c8d.png)

**Comment by neauoire** [comment]
Are you still getting this issue?

**Comment by kormyen** [comment]
(Welcome back to the internets!)

Negative. No error now.

**Comment by kormyen** [comment]
If I time travel to when I reported the bug, there is no bug, but I also tried time traveling to before your website existed and a similar (if not the same) bug appears 
![image](https://user-images.githubusercontent.com/836507/52922000-0b4ef600-3382-11e9-9b56-8a75db509118.png)

**Comment by neauoire** [comment]
that is super bizarre. It seems like the 9th of feb 2003 is not a valid time?!

**Comment by neauoire** [comment]
I will keep this open until I figure it out :)

**Comment by neauoire** [comment]
Fixed now :)
