### ISSUE TITLE
How can I use this?

### ISSUE THREAD

**Issue by ccorcos** [XXIIVV/Oscean#26]
I'm trying to figure out how run my own website like `https://wiki.xxiivv.com/` using that Rivan graph and everything... Are there any instructions on how to get this whole thing to work?

**Comment by neauoire** [comment]
There isn't, besides cloning the repo and poking around, you can ask me questions if you have some after trying it out. Or look at the forks, and ask their owners.

**Comment by ccorcos** [comment]
OK. I'm curious exactly how you use Riven to power the website.I found a link somewhere that showed a graph that looked like it was building templates serving the website with some DOM tree mapped out in the graph. 

But then I look at this repo (and read somewhere else that everything is built for the _Long Now_) and it appears that there's no build step and everything is generated at runtime in the browser. But where is this graph defined? Also, is this Riven graph for the wiki useful in the sense that it is productive for you to visualize and manipulate these processes or is it just a fun project?

**Comment by neauoire** [comment]
This [graph](wiki.xxiivv.com/riven.html), is built in [graph.js](https://github.com/XXIIVV/Oscean/blob/master/scripts/graph.js).

**Comment by neauoire** [comment]
It's just a fun project, it's nice to be able to map the data visually I guess. It was a curiosity at first to play with flow-based programming, but I never stopped using it after.

**Comment by ccorcos** [comment]
Oh there it is. Thanks for sharing!
