### ISSUE TITLE
How do I create one for myself & how do I use it?

### ISSUE THREAD

**Issue by SiGhTfOrbACQ** [XXIIVV/Oscean#27]
Looks like nirvana to me, especially the 26 “month” calendar. Need help, can not grok everything, and lots of new interesting ideas abound everywhere.

Title says it all. Need a howto...

**Comment by neauoire** [comment]
If you click `Download` or `Fork`, you should be able to download your down copy. 
It has no external dependencies, you should be able to just open the `index.html`, and start changing content in the databases.
