### ISSUE TITLE
Indental wiki link seems to be broken 

### ISSUE THREAD

**Issue by m0rphed** [XXIIVV/Oscean#40]
Encountered some problems while I was exploring **.ndtl** format used in project [memex](https://github.com/kormyen/memex), link to *Idential db* documentation seems to be broken:
https://wiki.xxiivv.com/#indental

It's sad, because I assume it is the only place where users could read about **ndtl** :cry:

**Comment by neauoire** [comment]
The docs is now located [here](https://wiki.xxiivv.com/oscean), and the parser is located [here](https://github.com/hundredrabbits/Libraries/blob/master/scripts/lib/indental.js).
