### ISSUE TITLE
https://wiki.xxiivv.com/traumae is a broken link

### ISSUE THREAD

**Issue by basinbaby** [XXIIVV/Oscean#43]
https://wiki.xxiivv.com/traumae is a broken link.

![image](https://user-images.githubusercontent.com/57834646/74094274-987ce480-4ad6-11ea-931e-ef560ba5a7e8.png)

**Comment by neauoire** [comment]
How did you end up there from? Traumae was renamed to [Lietal](https://wiki.xxiivv.com/site/lietal.html) many years ago.

**Comment by basinbaby** [comment]
It's linked on the description of this youtube video :D

https://youtu.be/_YXK1nepTPA

![image](https://user-images.githubusercontent.com/57834646/74097099-07bafe80-4b00-11ea-9f81-7b7edf6675a7.png)
