### ISSUE TITLE
broken link on lain to Nataniev

### ISSUE THREAD

**Issue by mininmobile** [XXIIVV/Oscean#46]
[lain](https://wiki.xxiivv.com/site/lain.html) attempts to link to [nataniev](https://wiki.xxiivv.com/site/nataniev.html), after i flipped the polarity i discovered the link on the page contains a capital unlike the actual nataniev page causing a broken link. we all make mistakes :p

**Comment by neauoire** [comment]
Thanks for the head's up :) I'll eventually make something that finds the broken link
