### ISSUE TITLE
Broken route from external site

### ISSUE THREAD

**Issue by inscripttech** [XXIIVV/Oscean#48]
Link from {usesthis} interview here: https://usesthis.com/interviews/devine.lu.linvega/

routes to: https://wiki.xxiivv.com/software

with error message: "destination could not be found".

**Comment by inscripttech** [comment]
overlooked issue #45 so as not to duplicate

**Comment by neauoire** [comment]
Added redirect page for broken link, contacted usesthis with corrected answers.
