### ISSUE TITLE
uxn hello world description seems inconsistent with code

### ISSUE THREAD

**Issue by mrshll** [XXIIVV/oscean#78]
https://github.com/XXIIVV/oscean/blob/master/src/inc/html/uxambly.htm#L58-L87

Could be that I first looked at uxn 20 minutes ago and am still understanding. But the description's `JSR2` opcode doesn't seem to appear in the code.

**Comment by neauoire** [comment]
Ah yes you're right :) I'll update the description of the hello world, thanks!

**Comment by neauoire** [comment]
Fixed in latest commit
