### ISSUE TITLE
How does lexicon syntax works?

### ISSUE THREAD

**Issue by istrigo** [XXIIVV/oscean#89]
In the lexicon file "~/src/database/lexicon" there are suffixes to the numbers i.e: 2;alicef 3,azolla. I've been reading the resources and comparing the differences between the compiled results, but didn't find any. Are they being used for marking a dead-end or orphan? Thanks.

**Comment by neauoire** [comment]
This is because I need to be extremely frugal with resources, but the numbers indicate depth, like

```
3;demo
4,superworker
4,supervisitor
5 dodecae
```
or
```
demo
-  superworker
-  supervisitor
--    dodecae
```
The runes are listed [here](https://github.com/XXIIVV/oscean/blob/main/src/oscean.tal#L3).

**Comment by istrigo** [comment]
Alright, let me know if I understood the runes:

- Portal rune lists all covers from child pages.
- Archive rune lists all text without photos from child pages .
- Album rune lists all photos attached to that page in order set by diary entry.

**Comment by neauoire** [comment]
yup! that's correct :)

**Comment by istrigo** [comment]
Nice to hear that. Thanks for your time :D
