### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by alex-bender** [XXIIVV/oscean#96]
[This](https://aliceffekt.bandcamp.com/album/a-pedestrian-paradise) page reads `Recording from Montreal's Piknik Electronic 2009 stage.
wiki.xxiivv.com/Live` which leads to 404

**Comment by neauoire** [comment]
Thank you, I've [changed](https://wiki.xxiivv.com/site/pedestrian_paradise.html) the link to the right url.
